trigger:
  branches:
    include:
      - main

pool:
  # vmImage: 'ubuntu-latest'
  name: 'Self-Hosted Pool'

variables:
  NODE_VERSION: '20'
  AZURE_APP_NAME: 'next-azure-app-service-test'  # Replace with your App Service name
  AZURE_SERVICE_CONNECTION: 'Azure subscription 1 (f70bdf5b-2914-4419-bcc9-bb1cafb0c176)'  # Replace with your service connection name

stages:
  - stage: BuildAndDeploy
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
          
          - script: |
              npm install
              npm run build
            displayName: 'Install Dependencies and Build'
            
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/out'  # Update this path to your build output directory
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              verbose: true
            displayName: 'Archive Build Output'

          - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            artifact: 'drop'
            displayName: 'Publish Artifact: drop'

      - job: Deploy
        dependsOn: Build
        steps:
          - download: current
            artifact: drop
            displayName: 'Download Artifact: drop'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              appName: $(AZURE_APP_NAME)
              package: '$(System.DefaultWorkingDirectory)/drop/$(Build.BuildId).zip'
              runtimeStack: 'NODE|20-lts'
